<?php

namespace App\Repositories;


use App\Models\Contact;

class ContactRepository extends ResourceRepository
{
    
    public function __construct(Contact $contact)
    {
        $this->model = $contact;
    }

    public function store(array $inputs)
    {
        if(auth()->check()){
            $inputs['email'] = auth()->user()->email;
        }

        return parent::store($inputs); // TODO: Change the autogenerated stub
    }
}